CREATE MATERIALIZED VIEW IF NOT EXISTS mv121 AS
SELECT
	item.i_manufact,
	catalog_sales.cs_ext_ship_cost,
	promotion.p_channel_dmail,
	date_dim.d_quarter_name,
	date_dim.d_day_name,
	customer_demographics.cd_education_status,
	catalog_sales.cs_net_profit,
	item.i_manager_id,
	catalog_sales.cs_net_paid,
	catalog_sales.cs_item_sk,
	catalog_sales.cs_list_price,
	item.i_class_id,
	customer_demographics.cd_dep_employed_count,
	date_dim.d_qoy,
	catalog_sales.cs_order_number,
	customer_demographics.cd_demo_sk,
	catalog_sales.cs_ext_wholesale_cost,
	customer_demographics.cd_credit_rating,
	promotion.p_channel_tv,
	date_dim.d_week_seq,
	date_dim.d_year,
	item.i_item_sk,
	item.i_product_name,
	item.i_wholesale_cost,
	customer_demographics.cd_purchase_estimate,
	customer_demographics.cd_marital_status,
	catalog_sales.cs_sold_date_sk,
	item.i_class,
	catalog_sales.cs_coupon_amt,
	catalog_sales.cs_ship_date_sk,
	catalog_sales.cs_bill_customer_sk,
	item.i_category,
	catalog_sales.cs_ext_discount_amt,
	customer_demographics.cd_gender,
	catalog_sales.cs_bill_hdemo_sk,
	date_dim.d_date_sk,
	item.i_category_id,
	date_dim.d_dow,
	catalog_sales.cs_wholesale_cost,
	catalog_sales.cs_quantity,
	catalog_sales.cs_sold_time_sk,
	date_dim.d_dom,
	item.i_color,
	customer_demographics.cd_dep_college_count,
	item.i_size,
	catalog_sales.cs_ext_sales_price,
	catalog_sales.cs_catalog_page_sk,
	item.i_units,
	catalog_sales.cs_call_center_sk,
	catalog_sales.cs_sales_price,
	catalog_sales.cs_ship_addr_sk,
	item.i_brand_id,
	catalog_sales.cs_net_paid_inc_tax,
	promotion.p_promo_sk,
	item.i_brand,
	item.i_current_price,
	date_dim.d_month_seq,
	item.i_item_id,
	catalog_sales.cs_bill_cdemo_sk,
	catalog_sales.cs_warehouse_sk,
	promotion.p_channel_event,
	catalog_sales.cs_ship_customer_sk,
	item.i_manufact_id,
	promotion.p_channel_email,
	customer_demographics.cd_dep_count,
	catalog_sales.cs_ship_mode_sk,
	item.i_item_desc,
	date_dim.d_moy,
	catalog_sales.cs_ext_list_price,
	date_dim.d_date,
	catalog_sales.cs_promo_sk,
	catalog_sales.cs_bill_addr_sk
FROM
	item,
	customer_demographics,
	date_dim,
	catalog_sales,
	promotion
WHERE
	customer_demographics.cd_gender = 'M'
	AND catalog_sales.cs_bill_cdemo_sk = customer_demographics.cd_demo_sk
	AND customer_demographics.cd_education_status = 'College'
	AND customer_demographics.cd_marital_status = 'S'
	AND catalog_sales.cs_item_sk = item.i_item_sk
	AND catalog_sales.cs_promo_sk = promotion.p_promo_sk
	AND catalog_sales.cs_sold_date_sk = date_dim.d_date_sk
	AND date_dim.d_year = 2000
	AND promotion.p_channel_email = 'N'
	AND promotion.p_channel_event = 'N'