CREATE MATERIALIZED VIEW IF NOT EXISTS mv252 AS
SELECT
	item.i_manufact,
	customer_address.ca_location_type,
	store_returns.sr_returned_date_sk,
	customer_address.ca_city,
	date_dim.d_day_name,
	item.i_manager_id,
	store.s_county,
	item.i_class_id,
	customer_demographics.cd_dep_employed_count,
	catalog_sales.cs_list_price,
	customer_address.ca_street_number,
	catalog_sales.cs_order_number,
	customer_address.ca_address_sk,
	catalog_returns.cr_call_center_sk,
	customer_demographics.cd_demo_sk,
	store_sales.ss_sold_date_sk,
	customer.c_first_sales_date_sk,
	household_demographics.hd_vehicle_count,
	customer.c_first_name,
	customer_address.ca_street_name,
	date_dim.d_week_seq,
	date_dim.d_year,
	item.i_product_name,
	store_sales.ss_ext_sales_price,
	store_returns.sr_item_sk,
	store_sales.ss_ext_tax,
	store.s_number_employees,
	customer_address.ca_gmt_offset,
	customer_demographics.cd_marital_status,
	catalog_returns.cr_item_sk,
	store_returns.sr_store_sk,
	catalog_returns.cr_return_quantity,
	catalog_sales.cs_sold_date_sk,
	item.i_class,
	income_band.ib_lower_bound,
	customer.c_current_hdemo_sk,
	customer.c_birth_day,
	store_sales.ss_sold_time_sk,
	customer.c_login,
	store_sales.ss_hdemo_sk,
	date_dim.d_date_sk,
	date_dim.d_dow,
	customer.c_birth_year,
	customer.c_current_addr_sk,
	catalog_sales.cs_wholesale_cost,
	catalog_sales.cs_quantity,
	store_returns.sr_net_loss,
	customer.c_birth_month,
	customer.c_customer_id,
	customer_demographics.cd_dep_college_count,
	catalog_returns.cr_order_number,
	catalog_returns.cr_return_amt_inc_tax,
	store.s_street_name,
	store.s_gmt_offset,
	catalog_sales.cs_ext_sales_price,
	catalog_sales.cs_catalog_page_sk,
	store_sales.ss_addr_sk,
	catalog_sales.cs_call_center_sk,
	household_demographics.hd_dep_count,
	catalog_returns.cr_store_credit,
	household_demographics.hd_demo_sk,
	catalog_sales.cs_net_paid_inc_tax,
	store.s_market_id,
	date_dim.d_month_seq,
	customer_address.ca_street_type,
	store_sales.ss_wholesale_cost,
	store_sales.ss_quantity,
	catalog_sales.cs_bill_cdemo_sk,
	promotion.p_channel_event,
	store.s_company_name,
	catalog_sales.cs_ship_customer_sk,
	store.s_state,
	item.i_manufact_id,
	store_returns.sr_reason_sk,
	income_band.ib_upper_bound,
	promotion.p_channel_email,
	customer_demographics.cd_dep_count,
	catalog_sales.cs_ship_mode_sk,
	customer_address.ca_suite_number,
	item.i_item_desc,
	date_dim.d_date,
	catalog_returns.cr_reversed_charge,
	catalog_sales.cs_ext_ship_cost,
	promotion.p_channel_dmail,
	store_sales.ss_promo_sk,
	date_dim.d_quarter_name,
	store_returns.sr_return_amt,
	store_sales.ss_store_sk,
	customer_address.ca_state,
	customer_demographics.cd_education_status,
	customer_address.ca_country,
	catalog_sales.cs_net_profit,
	catalog_sales.cs_net_paid,
	store_sales.ss_customer_sk,
	catalog_sales.cs_item_sk,
	date_dim.d_qoy,
	catalog_returns.cr_returned_date_sk,
	store_sales.ss_cdemo_sk,
	catalog_sales.cs_ext_wholesale_cost,
	customer.c_last_name,
	customer_address.ca_zip,
	customer_demographics.cd_credit_rating,
	store.s_store_sk,
	catalog_returns.cr_returning_addr_sk,
	promotion.p_channel_tv,
	item.i_item_sk,
	customer_address.ca_county,
	catalog_returns.cr_return_amount,
	item.i_wholesale_cost,
	store.s_store_id,
	customer_demographics.cd_purchase_estimate,
	store_sales.ss_ext_wholesale_cost,
	customer.c_current_cdemo_sk,
	catalog_returns.cr_refunded_cash,
	store_sales.ss_ext_list_price,
	customer.c_customer_sk,
	store_returns.sr_ticket_number,
	catalog_sales.cs_coupon_amt,
	catalog_sales.cs_ship_date_sk,
	catalog_sales.cs_bill_customer_sk,
	store.s_city,
	item.i_category,
	customer.c_salutation,
	catalog_sales.cs_ext_discount_amt,
	customer_demographics.cd_gender,
	catalog_sales.cs_bill_hdemo_sk,
	item.i_category_id,
	customer.c_first_shipto_date_sk,
	store.s_zip,
	store_sales.ss_ext_discount_amt,
	customer.c_birth_country,
	store.s_street_type,
	store_sales.ss_item_sk,
	income_band.ib_income_band_sk,
	catalog_sales.cs_sold_time_sk,
	date_dim.d_dom,
	item.i_color,
	store_returns.sr_cdemo_sk,
	store_sales.ss_coupon_amt,
	item.i_size,
	item.i_units,
	store.s_store_name,
	store_returns.sr_customer_sk,
	catalog_sales.cs_sales_price,
	catalog_sales.cs_ship_addr_sk,
	store_sales.ss_net_paid,
	household_demographics.hd_income_band_sk,
	item.i_brand_id,
	promotion.p_promo_sk,
	catalog_returns.cr_returning_customer_sk,
	item.i_brand,
	store_sales.ss_list_price,
	store_sales.ss_ticket_number,
	store_returns.sr_return_quantity,
	item.i_current_price,
	item.i_item_id,
	store.s_company_id,
	customer.c_last_review_date_sk,
	catalog_sales.cs_warehouse_sk,
	store.s_suite_number,
	household_demographics.hd_buy_potential,
	customer.c_email_address,
	catalog_returns.cr_net_loss,
	store_sales.ss_sales_price,
	catalog_sales.cs_ext_list_price,
	date_dim.d_moy,
	store_sales.ss_net_profit,
	catalog_sales.cs_promo_sk,
	catalog_returns.cr_catalog_page_sk,
	customer.c_preferred_cust_flag,
	catalog_sales.cs_bill_addr_sk,
	store.s_street_number
FROM
	item,
	household_demographics,
	catalog_returns,
	store,
	promotion,
	customer,
	customer_address,
	customer_demographics,
	date_dim,
	income_band,
	store_returns,
	catalog_sales,
	store_sales
WHERE
	customer.c_current_cdemo_sk = customer_demographics.cd_demo_sk
	AND store_sales.ss_customer_sk = customer.c_customer_sk
	AND customer.c_first_sales_date_sk = date_dim.d_date_sk
	AND customer.c_current_addr_sk = customer_address.ca_address_sk
	AND customer.c_current_hdemo_sk = household_demographics.hd_demo_sk
	AND customer.c_first_shipto_date_sk = date_dim.d_date_sk
	AND store_sales.ss_cdemo_sk = customer_demographics.cd_demo_sk
	AND household_demographics.hd_income_band_sk = income_band.ib_income_band_sk
	AND store_sales.ss_hdemo_sk = household_demographics.hd_demo_sk
	AND store_sales.ss_addr_sk = customer_address.ca_address_sk
	AND store_sales.ss_item_sk = item.i_item_sk
	AND store_sales.ss_item_sk = catalog_sales.cs_item_sk
	AND store_sales.ss_item_sk = store_returns.sr_item_sk
	AND store_sales.ss_sold_date_sk = date_dim.d_date_sk
	AND store_sales.ss_ticket_number = store_returns.sr_ticket_number
	AND store_sales.ss_store_sk = store.s_store_sk
	AND store_sales.ss_promo_sk = promotion.p_promo_sk
	AND (((item.i_color = 'purple') OR (item.i_color = 'burlywood') OR (item.i_color = 'indian') OR (item.i_color = 'spring') OR (item.i_color = 'floral') OR (item.i_color = 'medium')))
	AND catalog_sales.cs_item_sk = catalog_returns.cr_item_sk
	AND catalog_sales.cs_order_number = catalog_returns.cr_order_number
	AND catalog_returns.cr_refunded_cash > catalog_returns.cr_refunded_cash
	AND (date_dim.d_year = 1999 OR date_dim.d_year = 2000)