CREATE MATERIALIZED VIEW IF NOT EXISTS mv70 AS
SELECT
	date_dim.d_dow,
	catalog_sales.cs_ext_ship_cost,
	customer_address.ca_location_type,
	customer_address.ca_city,
	catalog_sales.cs_quantity,
	catalog_sales.cs_wholesale_cost,
	date_dim.d_quarter_name,
	date_dim.d_day_name,
	customer_address.ca_state,
	catalog_sales.cs_net_profit,
	customer_address.ca_country,
	catalog_sales.cs_net_paid,
	catalog_sales.cs_sold_time_sk,
	catalog_sales.cs_item_sk,
	catalog_sales.cs_list_price,
	catalog_returns.cr_returned_date_sk,
	date_dim.d_qoy,
	customer_address.ca_street_number,
	catalog_sales.cs_order_number,
	customer_address.ca_address_sk,
	date_dim.d_dom,
	catalog_returns.cr_call_center_sk,
	catalog_returns.cr_order_number,
	catalog_returns.cr_return_amt_inc_tax,
	catalog_sales.cs_ext_wholesale_cost,
	catalog_returns.cr_reversed_charge,
	call_center.cc_call_center_sk,
	customer_address.ca_street_name,
	catalog_sales.cs_ext_sales_price,
	catalog_sales.cs_catalog_page_sk,
	catalog_sales.cs_call_center_sk,
	customer_address.ca_zip,
	catalog_sales.cs_sales_price,
	catalog_sales.cs_ship_addr_sk,
	catalog_returns.cr_returning_addr_sk,
	date_dim.d_week_seq,
	catalog_returns.cr_store_credit,
	date_dim.d_year,
	catalog_sales.cs_net_paid_inc_tax,
	customer_address.ca_county,
	call_center.cc_name,
	call_center.cc_county,
	catalog_returns.cr_returning_customer_sk,
	catalog_returns.cr_return_amount,
	date_dim.d_month_seq,
	customer_address.ca_street_type,
	catalog_sales.cs_bill_cdemo_sk,
	catalog_sales.cs_warehouse_sk,
	catalog_sales.cs_ship_customer_sk,
	call_center.cc_manager,
	customer_address.ca_gmt_offset,
	catalog_returns.cr_item_sk,
	catalog_sales.cs_ship_mode_sk,
	catalog_returns.cr_refunded_cash,
	catalog_returns.cr_net_loss,
	customer_address.ca_suite_number,
	catalog_returns.cr_return_quantity,
	catalog_sales.cs_sold_date_sk,
	catalog_sales.cs_ext_list_price,
	catalog_sales.cs_coupon_amt,
	catalog_sales.cs_ship_date_sk,
	catalog_sales.cs_bill_customer_sk,
	date_dim.d_moy,
	date_dim.d_date,
	catalog_sales.cs_ext_discount_amt,
	catalog_sales.cs_promo_sk,
	catalog_returns.cr_catalog_page_sk,
	catalog_sales.cs_bill_addr_sk,
	call_center.cc_call_center_id,
	catalog_sales.cs_bill_hdemo_sk,
	date_dim.d_date_sk
FROM
	catalog_sales LEFT JOIN catalog_returns ON (catalog_sales.cs_order_number = catalog_returns.cr_order_number)	Join customer_address
	Join call_center
	Join date_dim
WHERE
	catalog_sales.cs_call_center_sk = call_center.cc_call_center_sk
	AND catalog_sales.cs_ship_date_sk = date_dim.d_date_sk
	AND catalog_sales.cs_ship_addr_sk = customer_address.ca_address_sk
	AND call_center.cc_county = 'Williamson County'
	AND (((date_dim.d_date >= cast('1970-01-01' as date) + interval 11719 days) AND (date_dim.d_date <= cast('1970-01-01' as date) + interval 11779 days)))
	AND customer_address.ca_state = 'GA'