CREATE MATERIALIZED VIEW IF NOT EXISTS mv139
AS
SELECT
	web_sales.ws_ship_mode_sk,
	store_sales.ss_hdemo_sk,
	item.i_brand_id,
	web_sales.ws_order_number,
	date_dim.d_qoy,
	web_sales.ws_ship_hdemo_sk,
	customer_address.ca_city,
	web_sales.ws_web_site_sk,
	store_sales.ss_list_price,
	web_sales.ws_sold_time_sk,
	item.i_manager_id,
	store_sales.ss_store_sk,
	customer_address.ca_street_name,
	item.i_class,
	store_sales.ss_ext_wholesale_cost,
	web_sales.ws_sales_price,
	item.i_item_id,
	date_dim.d_moy,
	web_sales.ws_bill_addr_sk,
	item.i_current_price,
	store_sales.ss_customer_sk,
	date_dim.d_week_seq,
	web_sales.ws_ext_ship_cost,
	item.i_manufact,
	item.i_units,
	web_sales.ws_ship_customer_sk,
	date_dim.d_quarter_name,
	web_sales.ws_wholesale_cost,
	store_sales.ss_sales_price,
	customer_address.ca_street_number,
	item.i_product_name,
	customer_address.ca_state,
	store_sales.ss_ext_discount_amt,
	store_sales.ss_promo_sk,
	item.i_color,
	web_sales.ws_ext_sales_price,
	store_sales.ss_wholesale_cost,
	customer_address.ca_country,
	customer_address.ca_suite_number,
	date_dim.d_dom,
	item.i_manufact_id,
	store_sales.ss_net_paid,
	store_sales.ss_quantity,
	customer_address.ca_location_type,
	item.i_brand,
	date_dim.d_month_seq,
	web_sales.ws_ship_date_sk,
	store_sales.ss_ext_sales_price,
	customer_address.ca_street_type,
	date_dim.d_date_sk,
	web_sales.ws_promo_sk,
	customer_address.ca_county,
	store_sales.ss_ticket_number,
	store_sales.ss_cdemo_sk,
	date_dim.d_date,
	item.i_class_id,
	item.i_item_desc,
	item.i_category,
	web_sales.ws_ext_list_price,
	item.i_size,
	customer_address.ca_zip,
	web_sales.ws_warehouse_sk,
	web_sales.ws_quantity,
	store_sales.ss_ext_list_price,
	web_sales.ws_web_page_sk,
	date_dim.d_year,
	customer_address.ca_address_sk,
	web_sales.ws_net_paid,
	store_sales.ss_net_profit,
	store_sales.ss_sold_date_sk,
	web_sales.ws_ext_discount_amt,
	store_sales.ss_addr_sk,
	web_sales.ws_ext_wholesale_cost,
	store_sales.ss_item_sk,
	store_sales.ss_coupon_amt,
	item.i_item_sk,
	store_sales.ss_sold_time_sk,
	web_sales.ws_list_price,
	item.i_wholesale_cost,
	web_sales.ws_sold_date_sk,
	customer_address.ca_gmt_offset,
	web_sales.ws_ship_addr_sk,
	date_dim.d_day_name,
	item.i_category_id,
	store_sales.ss_ext_tax,
	web_sales.ws_bill_customer_sk,
	web_sales.ws_net_profit,
	web_sales.ws_item_sk,
	date_dim.d_dow
FROM
	date_dim,
	store_sales,
	web_sales,
	customer_address,
	item
WHERE
	store_sales.ss_item_sk = item.i_item_sk
	AND store_sales.ss_sold_date_sk = date_dim.d_date_sk
	AND store_sales.ss_addr_sk = customer_address.ca_address_sk
	AND web_sales.ws_item_sk = item.i_item_sk
	AND item.i_category = 'Electronics'
	AND web_sales.ws_bill_addr_sk = customer_address.ca_address_sk
	AND web_sales.ws_sold_date_sk = date_dim.d_date_sk
	AND date_dim.d_moy = 5
	AND date_dim.d_year = 1998;