CREATE MATERIALIZED VIEW IF NOT EXISTS mv174
PARTITIONED BY (ws_sold_date_sk)
AS
SELECT
	web_sales.ws_ship_mode_sk,
	item.i_brand_id,
	web_sales.ws_order_number,
	customer.c_birth_month,
	date_dim.d_qoy,
	web_sales.ws_ship_hdemo_sk,
	customer_address.ca_city,
	web_sales.ws_bill_customer_sk,
	web_sales.ws_web_site_sk,
	web_sales.ws_sold_time_sk,
	item.i_manager_id,
	customer_address.ca_street_name,
	item.i_class,
	customer.c_birth_country,
	web_sales.ws_sales_price,
	customer.c_last_review_date_sk,
	item.i_item_id,
	date_dim.d_moy,
	web_sales.ws_bill_addr_sk,
	item.i_current_price,
	date_dim.d_week_seq,
	customer.c_current_cdemo_sk,
	web_sales.ws_ext_ship_cost,
	customer.c_last_name,
	item.i_manufact,
	item.i_units,
	customer.c_birth_day,
	customer.c_email_address,
	web_sales.ws_ship_customer_sk,
	date_dim.d_quarter_name,
	web_sales.ws_wholesale_cost,
	customer_address.ca_street_number,
	item.i_product_name,
	customer.c_birth_year,
	customer_address.ca_state,
	item.i_color,
	web_sales.ws_ext_sales_price,
	customer_address.ca_country,
	customer_address.ca_suite_number,
	date_dim.d_dom,
	item.i_manufact_id,
	customer.c_preferred_cust_flag,
	customer_address.ca_location_type,
	item.i_brand,
	date_dim.d_month_seq,
	web_sales.ws_ship_date_sk,
	customer_address.ca_street_type,
	date_dim.d_date_sk,
	web_sales.ws_promo_sk,
	customer_address.ca_county,
	date_dim.d_date,
	item.i_class_id,
	item.i_item_desc,
	customer.c_current_addr_sk,
	item.i_category,
	web_sales.ws_ext_list_price,
	customer.c_first_name,
	item.i_size,
	customer_address.ca_zip,
	web_sales.ws_warehouse_sk,
	web_sales.ws_quantity,
	web_sales.ws_web_page_sk,
	date_dim.d_year,
	customer_address.ca_address_sk,
	web_sales.ws_net_paid,
	web_sales.ws_ext_discount_amt,
	customer.c_first_shipto_date_sk,
	web_sales.ws_ext_wholesale_cost,
	customer.c_customer_sk,
	item.i_item_sk,
	web_sales.ws_list_price,
	item.i_wholesale_cost,
	web_sales.ws_sold_date_sk,
	customer_address.ca_gmt_offset,
	customer.c_customer_id,
	customer.c_login,
	web_sales.ws_ship_addr_sk,
	customer.c_first_sales_date_sk,
	date_dim.d_day_name,
	item.i_category_id,
	customer.c_salutation,
	web_sales.ws_net_profit,
	web_sales.ws_item_sk,
	date_dim.d_dow,
	customer.c_current_hdemo_sk
FROM
	date_dim,
	web_sales,
	customer,
	customer_address,
	item
WHERE
	(((substr(customer_address.ca_zip) OR (1) OR (5) = '85669') OR (substr(customer_address.ca_zip) OR (1) OR (5) = '86197') OR (substr(customer_address.ca_zip) OR (1) OR (5) = '88274') OR (substr(customer_address.ca_zip) OR (1) OR (5) = '83405') OR (substr(customer_address.ca_zip) OR (1) OR (5) = '86475') OR (substr(customer_address.ca_zip) OR (1) OR (5) = '85392') OR (substr(customer_address.ca_zip) OR (1) OR (5) = '85460') OR (substr(customer_address.ca_zip) OR (1) OR (5) = '80348') OR (substr(customer_address.ca_zip) OR (1) OR (5) = '81792')))
	AND customer.c_current_addr_sk = customer_address.ca_address_sk
	AND web_sales.ws_item_sk = item.i_item_sk
	AND web_sales.ws_bill_customer_sk = customer.c_customer_sk
	AND web_sales.ws_sold_date_sk = date_dim.d_date_sk
	AND (((item.i_item_sk = 2) OR (item.i_item_sk = 3) OR (item.i_item_sk = 5) OR (item.i_item_sk = 7) OR (item.i_item_sk = 11) OR (item.i_item_sk = 13) OR (item.i_item_sk = 17) OR (item.i_item_sk = 19) OR (item.i_item_sk = 23) OR (item.i_item_sk = 29)))
	AND date_dim.d_qoy = 2
	AND date_dim.d_year = 2001
DISTRIBUTE BY ws_sold_date_sk;