CREATE MATERIALIZED VIEW IF NOT EXISTS mv327
PARTITIONED BY (ws_sold_date_sk)
AS
SELECT
	web_returns.wr_returning_customer_sk,
	promotion.p_channel_tv,
	web_sales.ws_ship_mode_sk,
	web_returns.wr_item_sk,
	item.i_brand_id,
	web_sales.ws_order_number,
	date_dim.d_qoy,
	web_returns.wr_refunded_cdemo_sk,
	web_sales.ws_ship_hdemo_sk,
	web_site.web_name,
	web_returns.wr_refunded_addr_sk,
	web_sales.ws_web_site_sk,
	web_sales.ws_sold_time_sk,
	item.i_manager_id,
	item.i_class,
	promotion.p_channel_event,
	web_sales.ws_sales_price,
	item.i_item_id,
	date_dim.d_moy,
	item.i_current_price,
	web_sales.ws_bill_addr_sk,
	web_returns.wr_returning_addr_sk,
	date_dim.d_week_seq,
	web_sales.ws_ext_ship_cost,
	web_returns.wr_fee,
	web_site.web_site_id,
	item.i_manufact,
	item.i_units,
	web_sales.ws_ship_customer_sk,
	web_returns.wr_return_amt,
	web_returns.wr_net_loss,
	date_dim.d_quarter_name,
	web_sales.ws_wholesale_cost,
	web_returns.wr_web_page_sk,
	web_returns.wr_reason_sk,
	item.i_product_name,
	web_site.web_site_sk,
	item.i_color,
	web_sales.ws_ext_sales_price,
	web_returns.wr_returned_date_sk,
	web_returns.wr_returning_cdemo_sk,
	date_dim.d_dom,
	item.i_manufact_id,
	promotion.p_channel_dmail,
	item.i_brand,
	date_dim.d_month_seq,
	web_sales.ws_ship_date_sk,
	date_dim.d_date_sk,
	web_sales.ws_promo_sk,
	promotion.p_channel_email,
	date_dim.d_date,
	item.i_class_id,
	item.i_item_desc,
	item.i_category,
	web_sales.ws_ext_list_price,
	item.i_size,
	web_sales.ws_warehouse_sk,
	web_sales.ws_quantity,
	web_returns.wr_return_quantity,
	web_sales.ws_web_page_sk,
	date_dim.d_year,
	web_sales.ws_net_paid,
	web_returns.wr_refunded_cash,
	promotion.p_promo_sk,
	web_sales.ws_ext_discount_amt,
	web_sales.ws_ext_wholesale_cost,
	item.i_item_sk,
	web_sales.ws_list_price,
	item.i_wholesale_cost,
	web_sales.ws_sold_date_sk,
	web_site.web_company_name,
	web_sales.ws_ship_addr_sk,
	web_returns.wr_order_number,
	date_dim.d_day_name,
	item.i_category_id,
	web_sales.ws_bill_customer_sk,
	web_sales.ws_net_profit,
	web_sales.ws_item_sk,
	date_dim.d_dow
FROM
	web_sales LEFT OUTER JOIN web_returns ON (web_sales.ws_order_number = web_returns.wr_order_number AND web_sales.ws_item_sk = web_returns.wr_item_sk)	Join date_dim
	Join promotion
	Join item
	Join web_site
WHERE
	web_sales.ws_promo_sk = promotion.p_promo_sk
	AND web_sales.ws_item_sk = item.i_item_sk
	AND web_sales.ws_sold_date_sk = date_dim.d_date_sk
	AND web_sales.ws_web_site_sk = web_site.web_site_sk
	AND promotion.p_channel_tv = 'N'
	AND (((date_dim.d_date >= cast('1970-01-01' as date) + interval 11192 days) AND (date_dim.d_date <= cast('1970-01-01' as date) + interval 11222 days)))
DISTRIBUTE BY ws_sold_date_sk;