SELECT
	date_dim.d_dow,
	store.s_zip,
	store_sales.ss_promo_sk,
	date_dim.d_quarter_name,
	store_sales.ss_ext_discount_amt,
	date_dim.d_day_name,
	store_sales.ss_store_sk,
	customer_demographics.cd_education_status,
	store.s_street_type,
	store_sales.ss_item_sk,
	store_sales.ss_customer_sk,
	customer_demographics.cd_dep_employed_count,
	date_dim.d_qoy,
	store.s_county,
	date_dim.d_dom,
	customer_demographics.cd_dep_college_count,
	customer_demographics.cd_demo_sk,
	store_sales.ss_sold_date_sk,
	store.s_street_name,
	store_sales.ss_cdemo_sk,
	store_sales.ss_coupon_amt,
	store.s_gmt_offset,
	store_sales.ss_addr_sk,
	customer_demographics.cd_credit_rating,
	store.s_store_name,
	store.s_store_sk,
	date_dim.d_week_seq,
	date_dim.d_year,
	store_sales.ss_ext_sales_price,
	store.s_market_id,
	store_sales.ss_list_price,
	store_sales.ss_ticket_number,
	date_dim.d_month_seq,
	store_sales.ss_quantity,
	store_sales.ss_ext_tax,
	store_sales.ss_wholesale_cost,
	store.s_number_employees,
	store.s_company_id,
	store.s_store_id,
	store.s_company_name,
	customer_demographics.cd_purchase_estimate,
	store.s_state,
	store_sales.ss_ext_wholesale_cost,
	store.s_suite_number,
	customer_demographics.cd_marital_status,
	store_sales.ss_ext_list_price,
	customer_demographics.cd_dep_count,
	store_sales.ss_sales_price,
	store_sales.ss_sold_time_sk,
	date_dim.d_moy,
	date_dim.d_date,
	store_sales.ss_net_profit,
	store.s_city,
	store.s_street_number,
	customer_demographics.cd_gender,
	store_sales.ss_hdemo_sk,
	date_dim.d_date_sk,
	store_sales.ss_net_paid
FROM
	store_sales,
	customer_demographics,
	date_dim,
	store
WHERE
	customer_demographics.cd_gender = 'M'
	AND customer_demographics.cd_marital_status = 'S'
	AND customer_demographics.cd_education_status = 'College'
	AND store_sales.ss_cdemo_sk = customer_demographics.cd_demo_sk
	AND date_dim.d_year = 2002
	AND store_sales.ss_sold_date_sk = date_dim.d_date_sk
	AND store_sales.ss_store_sk = store.s_store_sk
	AND store.s_state = 'TN'