SELECT
	date_dim.d_dow,
	customer_address.ca_location_type,
	store.s_zip,
	customer_address.ca_city,
	store_sales.ss_promo_sk,
	date_dim.d_quarter_name,
	store_sales.ss_ext_discount_amt,
	date_dim.d_day_name,
	customer_address.ca_state,
	store_sales.ss_store_sk,
	store.s_street_type,
	customer_address.ca_country,
	store_sales.ss_customer_sk,
	store_sales.ss_item_sk,
	store.s_county,
	date_dim.d_qoy,
	customer_address.ca_street_number,
	customer_address.ca_address_sk,
	date_dim.d_dom,
	store_sales.ss_sold_date_sk,
	store.s_street_name,
	household_demographics.hd_vehicle_count,
	store_sales.ss_cdemo_sk,
	store.s_gmt_offset,
	store_sales.ss_coupon_amt,
	customer_address.ca_street_name,
	store_sales.ss_addr_sk,
	customer_address.ca_zip,
	store.s_store_name,
	store.s_store_sk,
	store_sales.ss_net_paid,
	household_demographics.hd_dep_count,
	household_demographics.hd_income_band_sk,
	date_dim.d_week_seq,
	household_demographics.hd_demo_sk,
	date_dim.d_year,
	store.s_market_id,
	store_sales.ss_ext_sales_price,
	store_sales.ss_ticket_number,
	customer_address.ca_county,
	store_sales.ss_list_price,
	date_dim.d_month_seq,
	customer_address.ca_street_type,
	store_sales.ss_ext_tax,
	store.s_number_employees,
	store_sales.ss_quantity,
	store.s_company_id,
	store_sales.ss_wholesale_cost,
	store.s_store_id,
	store.s_company_name,
	store.s_state,
	store_sales.ss_ext_wholesale_cost,
	store.s_suite_number,
	customer_address.ca_gmt_offset,
	store_sales.ss_ext_list_price,
	household_demographics.hd_buy_potential,
	customer_address.ca_suite_number,
	store_sales.ss_sales_price,
	date_dim.d_moy,
	store_sales.ss_sold_time_sk,
	store.s_city,
	date_dim.d_date,
	store_sales.ss_net_profit,
	store_sales.ss_hdemo_sk,
	date_dim.d_date_sk,
	store.s_street_number
FROM
	household_demographics,
	store,
	customer_address,
	date_dim,
	store_sales
WHERE
	store_sales.ss_addr_sk = customer_address.ca_address_sk
	AND store_sales.ss_sold_date_sk = date_dim.d_date_sk
	AND store_sales.ss_hdemo_sk = household_demographics.hd_demo_sk
	AND store_sales.ss_store_sk = store.s_store_sk
	AND (((store.s_city = 'Midway') OR (store.s_city = 'Fairview')))
	AND date_dim.d_dom <= 2
	AND date_dim.d_dom >= 1
	AND (((date_dim.d_year = 1999) OR (date_dim.d_year = 2000) OR (date_dim.d_year = 2001)))
	AND household_demographics.hd_vehicle_count = 3
	AND household_demographics.hd_dep_count = 4