SELECT
	item.i_manufact,
	store_returns.sr_returned_date_sk,
	promotion.p_channel_dmail,
	store_sales.ss_promo_sk,
	store_returns.sr_return_amt,
	date_dim.d_quarter_name,
	date_dim.d_day_name,
	store_sales.ss_store_sk,
	item.i_manager_id,
	store_sales.ss_customer_sk,
	date_dim.d_qoy,
	item.i_class_id,
	store.s_county,
	store_sales.ss_sold_date_sk,
	store_sales.ss_cdemo_sk,
	store.s_store_sk,
	promotion.p_channel_tv,
	date_dim.d_week_seq,
	date_dim.d_year,
	item.i_item_sk,
	item.i_product_name,
	store_sales.ss_ext_sales_price,
	store_returns.sr_item_sk,
	item.i_wholesale_cost,
	store_sales.ss_ext_tax,
	store.s_number_employees,
	store.s_store_id,
	store_sales.ss_ext_wholesale_cost,
	store_returns.sr_store_sk,
	store_sales.ss_ext_list_price,
	store_returns.sr_ticket_number,
	item.i_class,
	store_sales.ss_sold_time_sk,
	store.s_city,
	item.i_category,
	store_sales.ss_hdemo_sk,
	date_dim.d_date_sk,
	item.i_category_id,
	date_dim.d_dow,
	store.s_zip,
	store_sales.ss_ext_discount_amt,
	store.s_street_type,
	store_sales.ss_item_sk,
	store_returns.sr_net_loss,
	date_dim.d_dom,
	store_returns.sr_cdemo_sk,
	item.i_color,
	store.s_street_name,
	item.i_size,
	store_sales.ss_coupon_amt,
	store.s_gmt_offset,
	store_sales.ss_addr_sk,
	item.i_units,
	store.s_store_name,
	store_returns.sr_customer_sk,
	item.i_brand_id,
	promotion.p_promo_sk,
	store.s_market_id,
	item.i_brand,
	store_sales.ss_ticket_number,
	store_sales.ss_list_price,
	store_returns.sr_return_quantity,
	item.i_current_price,
	date_dim.d_month_seq,
	item.i_item_id,
	store_sales.ss_quantity,
	store.s_company_id,
	promotion.p_channel_event,
	store.s_company_name,
	store.s_state,
	item.i_manufact_id,
	store.s_suite_number,
	store_returns.sr_reason_sk,
	promotion.p_channel_email,
	store_sales.ss_sales_price,
	item.i_item_desc,
	date_dim.d_moy,
	date_dim.d_date,
	store_sales.ss_net_profit,
	store.s_street_number,
	store_sales.ss_wholesale_cost,
	store_sales.ss_net_paid
FROM
	store_sales LEFT JOIN store_returns ON (store_sales.ss_ticket_number = store_returns.sr_ticket_number AND store_sales.ss_item_sk = store_returns.sr_item_sk)	Join store
	Join item
	Join date_dim
	Join promotion
WHERE
	store_sales.ss_sold_date_sk = date_dim.d_date_sk
	AND store_sales.ss_item_sk = item.i_item_sk
	AND store_sales.ss_promo_sk = promotion.p_promo_sk
	AND store_sales.ss_store_sk = store.s_store_sk
	AND (((date_dim.d_date >= cast('1970-01-01' as date) + interval 11192 days) AND (date_dim.d_date <= cast('1970-01-01' as date) + interval 11222 days)))
	AND promotion.p_channel_tv = 'N'