SELECT
	inventory.inv_item_sk,
	date_dim.d_dow,
	item.i_manufact,
	item.i_category_id,
	store_sales.ss_promo_sk,
	date_dim.d_quarter_name,
	store_sales.ss_ext_discount_amt,
	date_dim.d_day_name,
	store_sales.ss_store_sk,
	item.i_manager_id,
	store_sales.ss_item_sk,
	store_sales.ss_customer_sk,
	inventory.inv_warehouse_sk,
	date_dim.d_qoy,
	item.i_class_id,
	date_dim.d_dom,
	item.i_color,
	store_sales.ss_sold_date_sk,
	store_sales.ss_cdemo_sk,
	store_sales.ss_coupon_amt,
	item.i_size,
	store_sales.ss_addr_sk,
	inventory.inv_date_sk,
	item.i_units,
	date_dim.d_week_seq,
	date_dim.d_year,
	item.i_item_sk,
	item.i_brand_id,
	item.i_product_name,
	store_sales.ss_ext_sales_price,
	item.i_brand,
	store_sales.ss_list_price,
	store_sales.ss_ticket_number,
	item.i_current_price,
	date_dim.d_month_seq,
	item.i_wholesale_cost,
	item.i_item_id,
	store_sales.ss_quantity,
	store_sales.ss_ext_tax,
	store_sales.ss_wholesale_cost,
	inventory.inv_quantity_on_hand,
	store_sales.ss_ext_wholesale_cost,
	item.i_manufact_id,
	store_sales.ss_ext_list_price,
	store_sales.ss_sales_price,
	item.i_item_desc,
	store_sales.ss_sold_time_sk,
	item.i_class,
	date_dim.d_moy,
	date_dim.d_date,
	store_sales.ss_net_profit,
	item.i_category,
	store_sales.ss_hdemo_sk,
	date_dim.d_date_sk,
	store_sales.ss_net_paid
FROM
	store_sales,
	item,
	date_dim,
	inventory
WHERE
	(((item.i_manufact_id = 129) OR (item.i_manufact_id = 270) OR (item.i_manufact_id = 821) OR (item.i_manufact_id = 423)))
	AND item.i_item_sk = store_sales.ss_item_sk
	AND item.i_item_sk = inventory.inv_item_sk
	AND (((inventory.inv_quantity_on_hand >= 100) AND (inventory.inv_quantity_on_hand <= 500)))
	AND inventory.inv_date_sk = date_dim.d_date_sk
	AND (((date_dim.d_date >= cast('1970-01-01' as date) + interval 11102 days) AND (date_dim.d_date <= cast('1970-01-01' as date) + interval 11162 days)))