SELECT
	date_dim.d_dow,
	customer_address.ca_location_type,
	customer_address.ca_city,
	store_sales.ss_promo_sk,
	store.s_zip,
	date_dim.d_quarter_name,
	store_sales.ss_ext_discount_amt,
	date_dim.d_day_name,
	customer_address.ca_state,
	store_sales.ss_store_sk,
	customer_address.ca_country,
	store.s_street_type,
	store_sales.ss_item_sk,
	store_sales.ss_customer_sk,
	date_dim.d_qoy,
	store.s_county,
	customer_address.ca_street_number,
	customer_address.ca_address_sk,
	date_dim.d_dom,
	store_sales.ss_sold_date_sk,
	store.s_street_name,
	store_sales.ss_cdemo_sk,
	store_sales.ss_coupon_amt,
	store.s_gmt_offset,
	customer_address.ca_street_name,
	store_sales.ss_addr_sk,
	customer_address.ca_zip,
	store_sales.ss_hdemo_sk,
	store.s_store_name,
	store.s_store_sk,
	date_dim.d_week_seq,
	date_dim.d_year,
	store_sales.ss_ext_sales_price,
	customer_address.ca_county,
	store_sales.ss_list_price,
	store_sales.ss_ticket_number,
	store.s_market_id,
	date_dim.d_month_seq,
	customer_address.ca_street_type,
	store_sales.ss_quantity,
	store_sales.ss_ext_tax,
	store.s_number_employees,
	store.s_company_id,
	store.s_store_id,
	store.s_company_name,
	store.s_state,
	store_sales.ss_ext_wholesale_cost,
	store.s_suite_number,
	customer_address.ca_gmt_offset,
	store_sales.ss_ext_list_price,
	customer_address.ca_suite_number,
	store_sales.ss_sales_price,
	date_dim.d_moy,
	store_sales.ss_sold_time_sk,
	date_dim.d_date,
	store_sales.ss_net_profit,
	store.s_city,
	store.s_street_number,
	store_sales.ss_wholesale_cost,
	date_dim.d_date_sk,
	store_sales.ss_net_paid
FROM
	customer_address,
	date_dim,
	store_sales,
	store
WHERE
	customer_address.ca_country = 'United States'
	AND store_sales.ss_addr_sk = customer_address.ca_address_sk
	AND (((customer_address.ca_state = 'VA') OR (customer_address.ca_state = 'TX') OR (customer_address.ca_state = 'MS')))
	AND (((customer_address.ca_state = 'TX') OR (customer_address.ca_state = 'OH') OR (customer_address.ca_state = '')))
	AND store_sales.ss_sold_date_sk = date_dim.d_date_sk
	AND store_sales.ss_store_sk = store.s_store_sk
	AND date_dim.d_year = 2001