SELECT
	item.i_manufact,
	catalog_sales.cs_ext_ship_cost,
	web_sales.ws_ship_hdemo_sk,
	store_sales.ss_promo_sk,
	date_dim.d_quarter_name,
	date_dim.d_day_name,
	store_sales.ss_store_sk,
	catalog_sales.cs_bill_addr_sk,
	catalog_sales.cs_net_profit,
	item.i_manager_id,
	catalog_sales.cs_net_paid,
	store_sales.ss_customer_sk,
	catalog_sales.cs_item_sk,
	date_dim.d_qoy,
	item.i_class_id,
	web_sales.ws_list_price,
	catalog_sales.cs_list_price,
	catalog_sales.cs_order_number,
	store_sales.ss_sold_date_sk,
	web_sales.ws_order_number,
	web_sales.ws_web_page_sk,
	store_sales.ss_cdemo_sk,
	catalog_sales.cs_ext_wholesale_cost,
	web_sales.ws_warehouse_sk,
	date_dim.d_week_seq,
	web_sales.ws_ship_date_sk,
	date_dim.d_year,
	item.i_item_sk,
	item.i_product_name,
	web_sales.ws_net_profit,
	store_sales.ss_ext_sales_price,
	web_sales.ws_sold_time_sk,
	item.i_wholesale_cost,
	store_sales.ss_ext_tax,
	web_sales.ws_sold_date_sk,
	store_sales.ss_ext_wholesale_cost,
	web_sales.ws_web_site_sk,
	store_sales.ss_ext_list_price,
	catalog_sales.cs_sold_date_sk,
	item.i_class,
	store_sales.ss_sold_time_sk,
	catalog_sales.cs_coupon_amt,
	catalog_sales.cs_ship_date_sk,
	catalog_sales.cs_bill_customer_sk,
	item.i_category,
	catalog_sales.cs_ext_discount_amt,
	web_sales.ws_ext_sales_price,
	store_sales.ss_hdemo_sk,
	web_sales.ws_ext_discount_amt,
	catalog_sales.cs_bill_hdemo_sk,
	date_dim.d_date_sk,
	item.i_category_id,
	date_dim.d_dow,
	web_sales.ws_ship_mode_sk,
	catalog_sales.cs_wholesale_cost,
	catalog_sales.cs_quantity,
	web_sales.ws_wholesale_cost,
	web_sales.ws_ext_list_price,
	store_sales.ss_ext_discount_amt,
	store_sales.ss_item_sk,
	catalog_sales.cs_sold_time_sk,
	date_dim.d_dom,
	web_sales.ws_ship_customer_sk,
	item.i_color,
	web_sales.ws_ship_addr_sk,
	web_sales.ws_ext_ship_cost,
	web_sales.ws_bill_addr_sk,
	item.i_size,
	store_sales.ss_coupon_amt,
	catalog_sales.cs_ext_sales_price,
	catalog_sales.cs_catalog_page_sk,
	store_sales.ss_addr_sk,
	item.i_units,
	catalog_sales.cs_call_center_sk,
	catalog_sales.cs_sales_price,
	catalog_sales.cs_ship_addr_sk,
	web_sales.ws_bill_customer_sk,
	item.i_brand_id,
	catalog_sales.cs_net_paid_inc_tax,
	item.i_brand,
	store_sales.ss_list_price,
	web_sales.ws_sales_price,
	store_sales.ss_ticket_number,
	date_dim.d_month_seq,
	item.i_current_price,
	item.i_item_id,
	store_sales.ss_quantity,
	web_sales.ws_ext_wholesale_cost,
	catalog_sales.cs_bill_cdemo_sk,
	catalog_sales.cs_warehouse_sk,
	web_sales.ws_item_sk,
	catalog_sales.cs_ship_customer_sk,
	item.i_manufact_id,
	web_sales.ws_net_paid,
	web_sales.ws_promo_sk,
	catalog_sales.cs_ship_mode_sk,
	web_sales.ws_quantity,
	store_sales.ss_sales_price,
	item.i_item_desc,
	date_dim.d_moy,
	catalog_sales.cs_ext_list_price,
	date_dim.d_date,
	store_sales.ss_net_profit,
	catalog_sales.cs_promo_sk,
	store_sales.ss_wholesale_cost,
	store_sales.ss_net_paid
FROM
	item LEFT JOIN store_sales ON (item.i_item_sk = store_sales.ss_item_sk)	Join web_sales
	Join date_dim
	Join catalog_sales
WHERE
	web_sales.ws_item_sk = item.i_item_sk
	AND web_sales.ws_sold_date_sk = date_dim.d_date_sk
	AND store_sales.ss_item_sk = item.i_item_sk
	AND catalog_sales.cs_item_sk = item.i_item_sk
	AND store_sales.ss_sold_date_sk = date_dim.d_date_sk
	AND date_dim.d_moy = 11
	AND catalog_sales.cs_sold_date_sk = date_dim.d_date_sk
	AND (((date_dim.d_year >= 1999) AND (date_dim.d_year <= 2001)))
	AND date_dim.d_year = 2001